server:
  port: 8080
spring:
  application:
    name: customer
  datasource:
    username: pguser
    url: jdbc:postgresql://postgres:5432/customer # jdbc:SGBD_NAME://CONTAINER_NAME_OF_SGBD:PORT/DATABASE_NAME
    password: pgpass
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  zipkin:
    enabled: true
    base-url: http://zipkin:9411  #ZIPKIN_CONTAINER_NAME:PORT
  rabbitmq:
    addresses: rabbitmq:5672  #RABBITMQ_CONTAINER_NAME:PORT
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka #SERVER_CONTAINER_NAME:PORT/SERVER_NAME
    fetch-registry: true
    registrer-with-eureka: true