server:
  port: 8080
spring:
  application:
    name: customer
  datasource:
    username: pguser
    url: jdbc:postgresql://localhost:5432/customer
    password: pgpass
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  zipkin:
    enabled: true
    base-url: http://localhost:9411
  rabbitmq:
    addresses: localhost:5672
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    registrer-with-eureka: true